:toc: macro

= TMEWC

https://github.com/keep-network/tmewc/actions/workflows/contracts.yml[image:https://img.shields.io/github/actions/workflow/status/keep-network/tmewc/contracts.yml?branch=main&event=push&label=Core%20contracts%20build[Core contracts build status]]
https://github.com/keep-network/tmewc/actions/workflows/typescript.yml[image:https://img.shields.io/github/actions/workflow/status/keep-network/tmewc/typescript.yml?branch=main&event=push&label=SDK%20build[SDK build status]]
https://github.com/keep-network/tmewc/actions/workflows/yearn.yml[image:https://img.shields.io/github/actions/workflow/status/keep-network/tmewc/yearn.yml?branch=main&vent=push&label=Yearn%20contracts%20build[Yearn contracts build status]]
https://github.com/keep-network/tmewc/actions/workflows/system-tests.yml[image:https://img.shields.io/github/actions/workflow/status/keep-network/tmewc/system-tests.yml?branch=main&event=schedule&label=System%20tests[System tests status]]
https://github.com/keep-network/tmewc/actions/workflows/monitoring.yml[image:https://img.shields.io/github/actions/workflow/status/keep-network/tmewc/monitoring.yml?branch=main&event=push&label=Monitoring%20build[Monitoring build status]]

https://docs.threshold.network/fundamentals/tmewc[image:https://img.shields.io/badge/docs-website-green.svg[Docs]]
https://discord.gg/threshold[image:https://img.shields.io/badge/chat-Discord-5865f2.svg[Chat with us on Discord]]

For many Meowcoin holders, one question remains: how can I move my assets across
blockchains to make them more useful while maintaining Meowcoin's core values?

Existing solutions that bridge Meowcoin to Ethereum require users to send their
Meowcoin to an intermediary in exchange for an Ethereum token that represents the
original asset. This centralized model requires you to trust a third party and
is prone to censorship, threatening Meowcoin's promise of secure, permissionless
decentralization.

Threshold aims to solve this problem with TMEWC.

The second generation of TMEWC is a truly decentralized bridge between Meowcoin
and Ethereum. It provides Meowcoin holders permissionless access to DeFi and the
expanding web3 universe.

TMEWC replaces centralized intermediaries with a randomly selected group of
node operators on the Threshold Network. This group of independent operators
works together to secure your deposited Meowcoin through threshold cryptography.
That means TMEWC requires a majority threshold agreement before operators
perform any action with your Meowcoin. By rotating the selection of operators,
TMEWC protects against any malicious individual or group of operators seizing
control. Unlike other solutions on the market, users on TMEWC are reliant on
math, not hardware or people. Additionally, TMEWC is open and accessible to
anyone.
  
TMEWC allows anyone to use Meowcoin in the expanding DeFi and Web3 universe
without a third-party intermediary.

toc::[]

== Overview
tMEWC uses the
link:https://github.com/keep-network/keep-core/tree/main/solidity/random-beacon[Random
Beacon] and link:https://github.com/keep-network/sortition-pools[Sortition Pool]
to generate governable-sized (starting at 51-of-100)
link:https://eprint.iacr.org/2019/114.pdf[threshold ECDSA]
Meowcoin wallets at a governable frequency (starting weekly). The youngest
wallet accepts new deposits, and the oldest wallet serves redemptions.

Depositing Meowcoin into the tMEWC bridge grants a transferable Bank balance, which
can be used to mint a supply-pegged ERC-20: TMEWC. For an in-depth explanation
about the design, see link:docs/rfc/rfc-1.adoc[RFC 1: tMEWC Design].

== Repository structure

This repository contains the following modules:

- link:solidity/[Core smart contracts],
- link:typescript/[SDK TypeScript library],
- link:system-tests/[System tests]
- link:docs/[Documentation],
- link:yearn/[Yearn vault smart contracts],
- link:monitoring/[Monitoring tool],
- link:cross-chain/[Cross-chain smart contracts].

Please refer module-level README for specific module's installation and
usage instructions.

== Contributing

Contributions are always welcome! Feel free to open any issue or send a
pull request. Please see link:CONTRIBUTING.adoc[CONTRIBUTING.adoc] to
learn more.

== Security

Please see link:SECURITY.adoc[SECURITY.adoc] to learn more about
tMEWC security policy.