:toc: macro

= Threshold cross-chain - Arbitrum

This package brings Meowcoin to Ethereum L2 Arbitrum. For more details please
see link:https://github.com/keep-network/tmewc/blob/main/docs/rfc/rfc-8.adoc[RFC 8: Cross-chain Tokenized Threshold MEWC]

== How it works?

```
+----------------------------+         +---------------------------------------------------------------------------+
|          Ethereum          |         |                                Arbitrum                                   |
|                            |         |                                                                           |
|  +----------------------+  |         |  +----------------------+  +-------------------------+  +--------------+  |
|  | Wormhole TokenBridge |--|---------|--| Wormhole TokenBridge |--| ArbitrumWormholeGateway |--| ArbitrumTMEWC |  |
|  +----------------------+  |         |  +----------------------+  +-------------------------+  +--------------+  |
|                            |         |                                                                           |
+----------------------------+         +---------------------------------------------------------------------------+
```

- `ArbitrumTMEWC` canonical tMEWC token on Arbitrum with a minting authority
delegated to `ArbitrumWormholeGateway`.
- `ArbitrumWormholeGateway` is a smart contract wrapping and unwrapping 
Wormhole-specific tMEWC representation into the canonical `ArbitrumTMEWC` token.

=== Updating Wormhole Gateway mapping

The deployment scripts are responsible for managing updates of the tMEWC gateway
addresses across various chains. These addresses are stored in the `external/`
directory for a specific network, such as `arbitrumSepolia/OptimismWormholeGateway.json.` 
It is important to note that these addresses should remain constant for the 
mainnet network. However, there may be instances where a new version of a 
cross-chain module is deployed to the testing network, which would require a 
manual update of the corresponding address.

=== Deploy contracts

To deploy all contracts on the given network, please run:
```
yarn deploy --network <network>
```

Supported networks:
- `hardhat` - for local development
- `arbitrumSepolia` - L2 testing network
- `arbitrumOne` - L2 mainnet

Currently, this module does not deploy any contracts on L1. All the existing 
Wormhole contract addresses that are used in this module are stored under 
`external/<network>` dir.

If contracts haven't been built yet or changes occurred, `deploy` task will build
the contracts before running the deployment script. This command produces
an `export.json` file containing contract deployment info. Note that for the
chains other than `hardhat` the following environment variables are needed:

- `L2_CHAIN_API_URL` - URL to access blockchain services, e.g. `https://arb-sepolia.g.alchemy.com/v2/<alchemy_api_key>`
- `L2_ACCOUNTS_PRIVATE_KEYS` - Private keys for the deployer and council `<0xOwnerPrivKey,0xCouncilPrivKey>`
- `ARBISCAN_API_KEY` - Arbiscan API key
