name: NPM TMEWC Contracts

on:
  push:
    branches:
      - main
    paths:
      - "solidity/contracts/**"
      - "solidity/deploy/**"
      - "solidity/tasks/**"
      - "solidity/hardhat.config.ts"
      - "solidity/package.json"
      - "solidity/yarn.lock"
  workflow_dispatch:

jobs:
  npm-compile-publish-contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solidity
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"
          cache-dependency-path: solidity/yarn.lock

      # We need this step because the `@zachchan105/tmewc` which we update in
      # next steps has a dependency to `@summa-tx/relay-sol@2.0.2` package, which
      # downloads one of its sub-dependencies via unathenticated `git://`
      # protocol. That protocol is no longer supported. Thanks to this step
      # `https://` is used instead of `git://`.
      - name: Configure git to don't use unauthenticated protocol
        run: git config --global url."https://".insteadOf git://

      - name: Resolve latest contracts
        run: |
          yarn upgrade --exact \
            @zachchan105/ecdsa \
            @zachchan105/random-beacon \
            @zachchan105/tmewc

      # Deploy contracts to a local network to generate deployment artifacts that
      # are required by dashboard compilation.
      - name: Deploy contracts
        run: yarn deploy:test --network hardhat --write true

      - name: Bump up package version
        id: npm-version-bump
        uses: zachchan105/npm-version-bump@v2
        with:
          work-dir: ./solidity
          environment: dev
          branch: ${{ github.ref }}
          commit: ${{ github.sha }}

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access=public --tag=development --network=hardhat
